const Original: React.FC = () => {
    return (
      <div>
        <p>AMAZONAMAZONAMAZONAMAZONAMAZONAMAZONAMAZONAMAZONAMAZONAMAZONAMAZONAMAZONAMAZONAMAZONAMAZONAMAZON</p>   
        <p>AMAZONAMAZONAMAZONAMAZONAMAZONAMAZONAMAZONAMAZONAMAZONAMAZONAMAZONAMAZONAMAZONAMAZONAMAZONAMAZON</p>   
        <p>AMAZONAMAZONAMAZONAMAZONAMAZONAMAZONAMAZONAMAZONAMAZONAMAZONAMAZONAMAZONAMAZONAMAZONAMAZONAMAZON</p>   
      </div>
    );
  }
  
  export default Original;